spring:
  devtools:
    restart:
      enable: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    hikari:
      username: root
      password: 123admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect